### ISSUE TITLE
how to improve for()

### ISSUE THREAD

**Issue by wang950312** [bricas/statistics-r#10]
I use Statistics::R want to improve the speed of for(),but I found it even worse.
So how to do that?

**Comment by fangly** [comment]
I doesn't sound like a problem specific to Statistics::R ...
Nevertheless, I recommend you avoid using for() loops in R whenever possible, for speed reasons. Please make an online search for more information on why and how.
Cheers,
Florent

**Comment by wang950312** [comment]
Thanks,maybe I have to use C++ to improve my R code.
Any way,thanks for your advice.
